import serial, time
ser = serial.Serial('COM7', 115200, timeout=.1)
time.sleep(1) #give the connection a second to settle
#input_value = input('Enter pixel position: ')
if True:
    #ser.write(input_value.encode())
    #time.sleep(2)
    ser.write(bytes('180', encoding="ascii"))
    print('1')
    time.sleep(2)
    ser.write(bytes('180', encoding="ascii"))
    print('2')
    time.sleep(2)
    ser.write(bytes('180', encoding="ascii"))
    print('3')
    time.sleep(2)
    ser.write(bytes('180', encoding="ascii"))
    print('1')
    time.sleep(2)
    ser.write(bytes('180', encoding="ascii"))
    print('1')
    time.sleep(2)
    # ser.close()
    # exit()